export const claseMago = Symbol('Mago')
export const claseGuerrero= Symbol('Guerrero')
export const claseClerigo= Symbol('Clérigo')
export const claseSaqueador = Symbol('Saqueador')
export const razaHumano = Symbol('Humano')
export const razaElfo = Symbol('Elfo')
export const razaEnano = Symbol('Enano')
export const razaHobbit = Symbol('Hobbit')